const products = [
  {
    name: "Men's Orange Black White Print Summer Sweater",
    img: "https://i.ibb.co/VLnJvLX/1.jpg",
    price: "175",
    off: "20",
    brand: "Wilson",
    category: "Men's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    stock: "12",
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Rainbow Jacquard Sweater for Women",
    img: "https://i.ibb.co/hHQ0rf8/2.jpg",
    price: "200",
    stock: "12",
    brand: "Wilson",
    category: "Men's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Apple 2022 Macbook Pro 18GB 256GB Laptop",
    img: "https://i.ibb.co/gwzKJXJ/3.jpg",
    price: "250",
    off: "10",
    stock: "12",
    brand: "Wilson",
    category: "Men's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Women Sweaters Autumn Winter Tops Slim Women",
    img: "https://i.ibb.co/YZY44hW/4.jpg",
    price: "300",
    stock: "12",
    brand: "Wilson",
    category: "Men's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Multicolor Rainbow Jacquard Sweater for Women",
    img: "https://i.ibb.co/VC0znys/5.jpg",
    price: "500",
    off: "30",
    stock: "12",
    brand: "Wilson",
    category: "Men's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Kickstar Black Huddy Cloth for Men",
    img: "https://i.ibb.co/tJtrzfC/6.jpg",
    price: "700",
    off: "10",
    stock: "12",
    brand: "Wilson",
    category: "Men's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Ruffle Neck Tiered Maxi Dress With Pin Tucks In Garden Floral",
    img: "https://i.ibb.co/sjsKhDc/7.jpg",
    price: "800",
    stock: "12",
    brand: "Wilson",
    category: "Men's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Bluetooth Wireless 5.0 Smart Watch",
    img: "https://i.ibb.co/7vkfSyq/8.jpg",
    price: "900",
    stock: "12",
    brand: "Wilson",
    category: "Men's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Apple 2022 Macbook Pro 18GB 256GB Laptop",
    img: "https://i.ibb.co/w7Y8mjz/9.jpg",
    price: "100",
    off: "50",
    stock: "12",
    brand: "Wilson",
    category: "Men's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Women Sweaters Autumn Winter Tops Slim Women",
    img: "https://i.ibb.co/x8ncxMb/10.jpg",
    price: "450",
    stock: "12",
    brand: "Wilson",
    category: "Men's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  //women category
  {
    name: "Multicolor Rainbow Jacquard Sweater for Women",
    img: "https://i.ibb.co/wwx5YFD/11.jpg",
    price: "175",
    off: "20",
    brand: "Levono",
    category: "Women's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    stock: "12",
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Men's Orange Black White Print Summer Sweater",
    img: "https://i.ibb.co/XLpvXFd/12.jpg",
    price: "200",
    stock: "12",
    brand: "Levono",
    category: "Women's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Rainbow Jacquard Sweater for Women",
    img: "https://i.ibb.co/vzppmLG/13.jpg",
    price: "250",
    off: "10",
    stock: "12",
    brand: "Levono",
    category: "Women's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Bluetooth Wireless 5.0 Smart Watch",
    img: "https://i.ibb.co/2FHMrLq/14.jpg",
    price: "300",
    stock: "12",
    brand: "Levono",
    category: "Women's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Apple 2022 Macbook Pro 18GB 256GB Laptop<",
    img: "https://i.ibb.co/0F8k7XT/15.jpg",
    price: "500",
    off: "30",
    stock: "12",
    brand: "Levono",
    category: "Women's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Women Sweaters Autumn Winter Tops Slim Women",
    img: "https://i.ibb.co/ZY14kKX/16.jpg",
    price: "700",
    off: "10",
    stock: "12",
    brand: "Levono",
    category: "Women's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Multicolor Rainbow Jacquard Sweater for Women",
    img: "https://i.ibb.co/f27DxL0/17.jpg",
    price: "800",
    stock: "12",
    brand: "Levono",
    category: "Women's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Men's Orange Black White Print Summer Sweater",
    img: "https://i.ibb.co/ydhYy4Y/18.jpg",
    price: "900",
    stock: "12",
    brand: "Levono",
    category: "Women's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Rainbow Jacquard Sweater for Women",
    img: "https://i.ibb.co/Nxn7FFq/19.jpg",
    price: "100",
    off: "50",
    stock: "12",
    brand: "Levono",
    category: "Women's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Bluetooth Wireless 5.0 Smart Watch",
    img: "https://i.ibb.co/Y3czSsK/20.jpg",
    price: "450",
    stock: "12",
    brand: "Levono",
    category: "Women's Fashion",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },

  //Computer electronics
  {
    name: "Bluetooth Wireless 5.0 Smart Watch",
    img: "https://i.ibb.co/N7mm7ym/21.jpg",
    price: "175",
    off: "20",
    brand: "PatPat",
    category: "Computer electronics",
    size: ["XL", "L", "M", "S", "XS"],
    stock: "12",
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Apple 2022 Macbook Pro 18GB 256GB Laptop",
    img: "https://i.ibb.co/tJcSFT1/22.jpg",
    price: "200",
    stock: "12",
    brand: "PatPat",
    category: "Computer electronics",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Women Sweaters Autumn Winter Tops Slim Women",
    img: "https://i.ibb.co/TcrcBpZ/23.jpg",
    price: "250",
    off: "10",
    stock: "12",
    brand: "PatPat",
    category: "Computer electronics",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Multicolor Rainbow Jacquard Sweater for Women",
    img: "https://i.ibb.co/pQDffH0/24.jpg",
    price: "300",
    stock: "12",
    brand: "PatPat",
    category: "Computer electronics",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Women Sweaters Autumn Winter Tops Slim Women<",
    img: "https://i.ibb.co/nsYYNsS/25.jpg",
    price: "500",
    off: "30",
    stock: "12",
    brand: "PatPat",
    category: "Computer electronics",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Multicolor Rainbow Jacquard Sweater for Women",
    img: "https://i.ibb.co/f1P9f00/26.jpg",
    price: "700",
    off: "10",
    stock: "12",
    brand: "PatPat",
    category: "Computer electronics",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: " Kickstar Black Huddy Cloth for Men",
    img: "https://i.ibb.co/YjYSLqv/27.jpg",
    price: "800",
    stock: "12",
    brand: "PatPat",
    category: "Computer electronics",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: " Ruffle Neck Tiered Maxi Dress With Pin Tucks In Garden Floral",
    img: "https://i.ibb.co/cLL4nhY/28.jpg",
    price: "900",
    stock: "12",
    brand: "PatPat",
    category: "Computer electronics",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Apple 2022 Macbook Pro 18GB 256GB Laptop",
    img: "https://i.ibb.co/xM6PVBd/29.jpg",
    price: "100",
    off: "50",
    stock: "12",
    brand: "PatPat",
    category: "Computer electronics",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
  {
    name: "Women Sweaters Autumn Winter Tops Slim Women",
    img: "https://i.ibb.co/ZVQ4K38/30.jpg",
    price: "450",
    stock: "12",
    brand: "PatPat",
    category: "Computer electronics",
    size: ["XL", "L", "M", "S", "XS"],
    numOfReviews: "123",
    description:
      "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
  },
];
